In [66]:
import numpy as np

#矩阵求逆
from numpy import linalg as lg  
# define a vector
vector = np.array([1,2,3,4])

# define a matrix
matrix = np.array([[1,'t'], [2, 'j'], [3, 'k'], [4,'f']])

print(vector, matrix)

# define a vector by list 
nparray = np.array([i for i in range(10)])

nparray[0] = 10 
print(nparray)

[1 2 3 4] [['1' 't']
 ['2' 'j']
 ['3' 'k']
 ['4' 'f']]
[10  1  2  3  4  5  6  7  8  9]


In [30]:
a = np.zeros(10)
print(a)
a.dtype # float64 

np.zeros(10, dtype=int)

# create n-d array with value equals 0
np.zeros(shape = (3,4))

# create n-d array with value equals 1 
np.ones(shape = (3,4))

# create n-d array with value equals k
np.full((3,4), 128)

np.arange(0, 20, 2)  # 与Python中的range方法相似，arange也是前闭后开的方法

np.linspace(0, 10, 5) # （前闭后闭）来对Numpy矩阵进行等分

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
# create random array 
np.random.randint(0, 10, size = 10)
np.random.randint(0, 99, (5,5))
np.random.seed(1)

# create random array from 0 to 1
np.random.random((5,5,5))

# create random array from normal distribution
np.random.normal(0, 1, 10)

a = np.arange(15).reshape(3,5)
print(a.shape) # return a tuple
# a.reshape(15,-1) # row
# a.reshape(-1,15) # column

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[:,1] # 左闭右开
b[0:2, 2] 
b[0, 1:3] 

(3, 5)


array([2, 3])

In [71]:
# matrix manipulation/operation
# 矩阵运算
myones = np.ones((3,3))
myeye = np.eye(3)
print(myeye)
print(myones - myeye)

mymatrix = np.array([[1,2,3],[4,5,6]])
a = np.array([[1,2],[3,4],[5,6]])
print(mymatrix.shape[1] == a.shape[0]) #确认第一个矩阵列数 == 第二个矩阵行数
print(a.dot(mymatrix))

a = np.array([[1,2],[3,4]]) #求逆矩阵需要 行列相等
Inva = lg.inv(a)
print(a.dot(Inva))
print(Inva.dot(a).astype(int)) # 数据类型转换

mymatrix
print(mymatrix.sum(axis=0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
True
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1 0]
 [0 0]]


In [90]:
# arg返回索引
index = np.argmax([1,2,3,4,5]) 
print(index) # 从0开始噢

x = np.arange(15)
print(x)
np.random.shuffle(x) # 注意一下这里
print(x)
# arg返回对于排序（从小到大）的索引
sx = np.argsort(x)
print(sx)

4
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2 11  9 12  1 14 13  6  0 10  8  3  5  7  4]
[ 8  4  0 11 14 12  7 13 10  2  9  1  3  6  5]


In [104]:
# 用数组索引另一个数组
x = np.arange(15)
ind = np.array([[9,1,3,4],[4,5,6,7],[1,4,5,6]])
print(x[ind])

# 索引二维数组
y = np.arange(16)
y = y.reshape(4,-1)
print(y)
row = np.array([0,1,3])
column = np.array([1,2,3])
print('---')
print(y[row, column]) # 取对应的点
print(y[1:3, column]) # 取index为1，2行，对应的column点

[[9 1 3 4]
 [4 5 6 7]
 [1 4 5 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
---
[ 1  6 15]
[[ 5  6  7]
 [ 9 10 11]]
